### ISSUE TITLE
Wrong autocompletion if \begin{...} and \end{...} are in the same line

### ISSUE THREAD

**Issue by kubkon** [Focus/latexer#12]
The package does not seem to check if for a `\begin{..}` there is a matching `\end{...}` in the same line. Instead, it overeagerly inserts the matching `\end{...}` when a new line is inserted.

In order to replicate, consider an example:

``` latex
\begin{equation}
  \begin{pmatrix} v1\\ v2 \end{pmatrix}
\end{equation}
```

If you then insert a new line after `\end{pmatrix}`, an additional `\end{pmatrix}` will be inserted below it:

``` latex
\begin{equation}
  \begin{pmatrix} v1\\ v2 \end{pmatrix}
    % cursor moved to the new line
  \end{pmatrix} % <-- this statement was autocompleted
\end{equation}
```

**Comment by redw0lf** [comment]
I hope I'm posting this in the correct issue.. At least it sounds like a similar problem to me:

The same/sth. similar occurs if you have more than one of the same environment (e.g. nested `\begin{itemize} ... \end{itemize}`)  Somehow it autocompletes anywhere after the first item. If i click in the first \item row

to replicate

```
\begin{itemize}
    \item aaaaaa
    \item b
    \begin{itemize} % no autocompletion here
        \item abc
    \end{itemize} % this end is not autocompleted!!!
\end{itemize}
```

now if you click anywhere in the `aaaaaa` and type sth it will autocomplete the first `\begin{itemize}` and it's hard to fix and remove this autocompletion (because it keeps reapearing).

result after clicking in the `aaaaaa` and writing a b:

```
\begin{itemize}
    \item aaab
    \end{itemize}aaa
    \item b
    \begin{itemize} % no autocompletion here
        \item abc
    \end{itemize} % this end is not autocompleted!!!
\end{itemize}
```

**Comment by Focus** [comment]
Thanks to both of you for the bug reports. I have fixed the bug of kubkon. The nesting bug that redw0lf reported is somewhat harder to fix. I have opened up a new bug report for this #15
