### ISSUE TITLE
Wrong project path

### ISSUE THREAD

**Issue by gasteigerjo** [Focus/latexer#18]
I am using latexer under Windows 10 64-bit. When trying to use a multifile environment by writing `"%!TEX root = thesis.tex"` I get the following error message:

```
"could not load content of C:\Users\Johannes\AppData\Local\atom\app-1.0.5\thesis.tex"
```

Where `C:\Users\Johannes\AppData\Local\atom\app-1.0.5` is the directory of atom's binary and not the project folder.

Also, in the root file itself, neither ref nor cite autocompletion works. It looks like the path you get by invoking `@editor.getPath()` is not correct. As far as I have seen, this function is deprecated and should be replaced by `getPaths()` anyway. Apart from that, maybe replace it by a completely different function, which directly resolves the path of the current file and use the folder in that path instead?

Edit: If I open the file by right-click, it works. If I open the complete folder by right-click->Open with atom, it doesn't. Neither does it when I open Atom using the start menu and then open the file within Atom.

**Comment by tthmok** [comment]
I've found that some of these issues are due to the filepath seperator having hard coded slashes so it doesn't work on Windows.

For example I changed places where I found things like this

```
    lastIndexOf("/")
```

to

```
    lastIndexOf("\\")
```

So that fixes the problem locally for me but I'm sure there must be a way to get at the OS file path separator rather than hard coding it.

I also went and changed how the initial basePath is found since as you said `@editor.getPath()` is deprecated. Altered the function getBibFiles in cite-view.coffee

```
getBibFiles: ->
    editor = atom.workspace.getActivePaneItem()
    file = editor?.buffer?.file
    basePath = file?.path
    #basePath = @editor.getPath()
    if basePath.lastIndexOf("\\") isnt -1
      basePath = basePath.substring 0, basePath.lastIndexOf("\\")
    ...
    ...
```

**Comment by Focus** [comment]
I don't have a windows PC at hand so I cannot check if tthmok's fix works. I hope this solves the problem here.
