### ISSUE TITLE
Autocomplete never triggers

### ISSUE THREAD

**Issue by DrBones** [Focus/latexer#4]
The install from the package manager worked fine but typing either "\cite{" or "\begin{equation}" in a *.tex file does not trigger the autocompletion. The file contains a \bibliography{thesisbib}.

Atom version: 0.194.0
latexer version 0.2.2

Other packages installed:
language-latex
vim-mode
project-manager
autocomplete-plus
minimap

I tried disabling the other packages to no avail. Please advise how I can debug this further. Can I somehow tell if the package is "running"?. I am fairly new to atom/javascript but I am willing to learn :). Thanks

**Comment by Focus** [comment]
Thanks for the report. Have you tried opening up a saved .tex file?

**Comment by DrBones** [comment]
Thanks for your quick reply. Indeed, if I open a saved .tex file it triggers. Apparently just saving a file as .tex and setting the Syntax in the Lower right corner is not enough. Thanks! Nice piece of software :)
Although it seems, the \bibliography{something.bib} is still needed. I get a 'no file or directory found' error if I leave the .bib out. The current version of latexer is 0.2.3

On a side note, if I choose a citation the focus does not return to the editor, I have to press "Tab" once to have the cursor back. Is this normal or a result of some weird settings I have? It happens with and without vim-mode. Should I open new issues for those? 

Thank you again and have a great weekend!

**Comment by Focus** [comment]
Yes this issue is fixed in 0.2.3, it should now realise when you save a file and adjust accordingly (it triggers when the title of the file ends in .tex).

As for the other two issues. The .bib should work fine with 0.2.3. If there are any problems you should open a new ticket (with the info from the crash). The focus issue is again something that I don't have. That seems very odd that you have to do this. You can try to disable every other package and try, if you can narrow it down to a package (or not) please open up a new report and I'll fix it.

Have a nice weekend as well :)
